#!/bin/sh

set -e

if [ $(id -u) -ne 1000 ]
then
    cd /home
    exec sudo -u $(id -n -u 1000) "$0" "$@"
fi

loginctl enable-linger $(id -u)
trap "loginctl disable-linger $(id -u)" EXIT

DBOX=callioperennspiel
IMAGE=docker.io/library/ubuntu:24.04

distrobox create -Y --name ${DBOX} --image ${IMAGE}

distrobox enter ${DBOX} -- sudo apt upgrade -y
distrobox enter ${DBOX} -- sudo apt install -y git python3-dev python3-tk build-essential python3-pynput python3-serial python3-pygame python3-sklearn python3-pandas python3-wheel vim x11-xserver-utils

distrobox enter ${DBOX} -- sudo git clone https://github.com/telekom/ki-in-schulen.git /usr/local/share/ki-in-schulen || distrobox enter ${DBOX} -- sh -c "cd /usr/local/share/ki-in-schulen ; sudo git pull"
