#!/bin/sh

set -e

sudo dbus-run-session flatpak update --system -y
dbus-run-session flatpak update --user -y

sudo env CLEAN_UNWANTED_PACKAGES=${CLEAN_UNWANTED_PACKAGES} dasi-flatpak-install

dasi-callioperennspiel-update
