#!/bin/sh

set -e

loginctl enable-linger $(id -u)
trap "loginctl disable-linger $(id -u)" EXIT

sudo dasi-flatpak-install

sudo dbus-run-session flatpak update --system -y
dbus-run-session flatpak update --user -y

dasi-callioperennspiel-update
